name: build-and-push-link-upcloud

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - staging
    paths:
      - 'bskylink/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: ./Dockerfile.bskylink
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ github.workspace }}/speakeasy-link.tar
          tags: speakeasy-link-image:latest

      - name: Gzip Docker Image
        run: |
          gzip -c ${{ github.workspace }}/speakeasy-link.tar > ${{ github.workspace }}/speakeasy-link.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: speakeasy-link-tar-gz
          path: ${{ github.workspace }}/speakeasy-link.tar.gz

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: speakeasy-link-tar-gz
          path: ${{ github.workspace }}

      - name: Copy Docker Image to UpCloud Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ github.workspace }}/speakeasy-link.tar.gz
          target: /home/speakeasy

      - name: Deploy and Run Docker Image on UpCloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop speakeasy-link || true
            docker rm speakeasy-link || true
            gunzip -f /home/speakeasy/github/workspace/speakeasy-link.tar.gz &&
            docker load --input /home/speakeasy/github/workspace/speakeasy-link.tar &&
            docker run -d -p 127.0.0.1:8103:8103 --restart=unless-stopped --name speakeasy-link speakeasy-link-image:latest
            

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: speakeasy-link-tar-gz
          path: ${{ github.workspace }}

      - name: Copy Docker Image to UpCloud Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ github.workspace }}/speakeasy-link.tar.gz
          target: /home/speakeasy

      - name: Deploy and Run Docker Image on UpCloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop speakeasy-link || true
            docker rm speakeasy-link || true
            gunzip -f /home/speakeasy/github/workspace/speakeasy-link.tar.gz &&
            docker load --input /home/speakeasy/github/workspace/speakeasy-link.tar &&
            docker run -d -p 127.0.0.1:8103:8103 --restart=unless-stopped --name speakeasy-link speakeasy-link-image:latest
            