name: build-and-push-bskyweb-upcloud

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - feature/deploy-upcloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/speakeasy-client.tar
          build-args: |
            EXPO_PUBLIC_BUNDLE_IDENTIFIER=${{ steps.vars.outputs.sha_short }}
          tags: speakeasy-client-image:latest

      - name: Gzip Docker Image
        run: |
          gzip -c ${{ runner.temp }}/speakeasy-client.tar > ${{ runner.temp }}/speakeasy-client.tar.gz

      - name: Copy Docker Image to UpCloud Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ runner.temp }}/speakeasy-client.tar.gz
          target: /home/speakeasy

      - name: Deploy and Run Docker Image on UpCloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop speakeasy-client || true
            docker rm speakeasy-client || true
            gunzip -c /home/speakeasy/speakeasy-client.tar.gz | docker load
            docker run -d -p 80:80 --name speakeasy-client speakeasy-client-image:latest
