name: build-and-push-bskyweb

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=min
          outputs: type=docker,dest=${{ github.workspace }}/speakeasy-client.tar
          build-args: |
            EXPO_PUBLIC_BUNDLE_IDENTIFIER=${{ steps.vars.outputs.sha_short }}
          tags: speakeasy-client-image:latest

      - name: Gzip Docker Image
        run: |
          gzip -c ${{ github.workspace }}/speakeasy-client.tar > ${{ github.workspace }}/speakeasy-client.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: speakeasy-client-tar-gz
          path: ${{ github.workspace }}/speakeasy-client.tar.gz
  
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: speakeasy-client-tar-gz
          path: ${{ github.workspace }}

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: ${{ github.workspace }}/speakeasy-client.tar.gz
          target: /home/speakeasy
          strip_components: 5

      - name: Deploy and Run Docker Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker stop speakeasy-client || true
            docker rm speakeasy-client || true
            gunzip -f /home/speakeasy/github/workspace/speakeasy-client.tar.gz &&
            docker load --input /home/speakeasy/github/workspace/speakeasy-client.tar &&
            docker run -d -p 127.0.0.1:8100:8100 --restart=unless-stopped --name speakeasy-client -e ATP_APPVIEW_HOST=https://api.bsky.app speakeasy-client-image:latest /usr/bin/bskyweb serve

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: speakeasy-client-tar-gz
          path: ${{ github.workspace }}

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: ${{ github.workspace }}/speakeasy-client.tar.gz
          target: /home/speakeasy

      - name: Deploy and Run Docker Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker stop speakeasy-client || true
            docker rm speakeasy-client || true
            gunzip -f ./home/runner/work/speakeasy/speakeasy/speakeasy-client.tar.gz &&
            docker load --input ./home/runner/work/speakeasy/speakeasy/speakeasy-client.tar &&
            docker run -d -p 127.0.0.1:8100:8100 --restart=unless-stopped --name speakeasy-client -e ATP_APPVIEW_HOST=https://api.bsky.app speakeasy-client-image:latest /usr/bin/bskyweb serve
            