name: Deploy Nginx Configuration

on:
  push:
    branches: [ main, staging, feature/nginx-ci ]
    paths:
      - 'infra/nginx/**'
      - .github/workflows/nginx-deploy.yml
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    timeout-minutes: 5
    env:
      TARGET_DIR: "/home/speakeasy/nginx-configs/"
    
    steps:
      - uses: actions/checkout@v4

      - name: Process nginx config
        env:
          MAIN_DOMAIN: ${{ vars.MAIN_DOMAIN }}
          EMBED_DOMAIN: ${{ vars.EMBED_DOMAIN }}
          CARD_DOMAIN: ${{ vars.CARD_DOMAIN }}
        run: |
          sed -e "s/{{MAIN_DOMAIN}}/${{ env.MAIN_DOMAIN }}/g" \
              -e "s/{{EMBED_DOMAIN}}/${{ env.EMBED_DOMAIN }}/g" \
              -e "s/{{CARD_DOMAIN}}/${{ env.CARD_DOMAIN }}/g" \
              infra/nginx/sites-available/speakeasy.template > infra/nginx/sites-available/speakeasy
          
          # Debug information
          echo "Current directory:"
          pwd
          echo "Workspace directory:"
          echo ${{ github.workspace }}
          echo "Directory contents:"
          ls -la
          echo "Infra directory contents:"
          ls -la infra/
          echo "Nginx directory contents:"
          ls -la infra/nginx/
          echo "Sites-available directory contents:"
          ls -la infra/nginx/sites-available/
          echo "Checking if files exist:"
          [ -f infra/nginx/sites-available/speakeasy ] && echo "speakeasy exists" || echo "speakeasy missing"
          [ -f infra/nginx/sites-available/default ] && echo "default exists" || echo "default missing"
          [ -f infra/nginx/nginx.conf ] && echo "nginx.conf exists" || echo "nginx.conf missing"

      - name: Create target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: mkdir -p ${{ env.TARGET_DIR }}

      - name: Upload nginx configs
        run: |
          # Create SSH key file
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/deploy_key
          
          # Copy files using scp
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ./infra/nginx/sites-available/speakeasy \
            ./infra/nginx/sites-available/default \
            ./infra/nginx/nginx.conf \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ env.TARGET_DIR }}
          
          # Clean up SSH key
          rm ~/.ssh/deploy_key

      - name: Deploy and reload nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo /usr/local/bin/deploy-nginx.sh ${{ env.TARGET_DIR }}/speakeasy ${{ env.TARGET_DIR }}/default ${{ env.TARGET_DIR }}/nginx.conf &&
            rm -rf ${{ env.TARGET_DIR }}
