name: Deploy Nginx Configuration

on:
  push:
    branches: [ main, staging, feature/nginx-ci ]
    paths:
      - 'infra/nginx/**'
      - .github/workflows/nginx-deploy.yml
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4

      - name: Process nginx config
        run: |
          sed -e "s/{{MAIN_DOMAIN}}/${{ env.MAIN_DOMAIN }}/g" \
              -e "s/{{EMBED_DOMAIN}}/${{ env.EMBED_DOMAIN }}/g" \
              -e "s/{{CARD_DOMAIN}}/${{ env.CARD_DOMAIN }}/g" \
              infra/nginx/sites-available/speakeasy.template > infra/nginx/sites-available/speakeasy

      - name: Deploy nginx configs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            "infra/nginx/sites-available/speakeasy"
            "infra/nginx/sites-available/default"
            "infra/nginx/nginx.conf"
          target: "~/nginx-configs"
          strip_components: 0

      - name: Test and reload nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo cp ~/nginx-configs/speakeasy /etc/nginx/sites-available/ &&
            sudo cp ~/nginx-configs/default /etc/nginx/sites-available/ &&
            sudo cp ~/nginx-configs/nginx.conf /etc/nginx/ &&
            if sudo nginx -t; then
              sudo systemctl reload nginx &&
              rm -rf ~/nginx-configs
            else
              echo "Nginx configuration test failed. Aborting reload."
              exit 1 